application: biocurious-sensordata
version: 1
runtime: python27
api_version: 1
threadsafe: no


handlers: 

- url: /(.*) 
  static_files: static/\1 
  upload: static/sensordata.html

- url: /(.*)  
  script: main.py


libraries:
- name: webapp2
  version: "2.5.1"
